=== statisticsnorway/microdata-datastore-builder/validate/JsonSchema_DataSet.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "definitions": {
        "dateType": {
            "$comment": "Type for the date format YYYY-MM-DD. (Python package jsonschema missing support for JSON Schema date format.)",
            "type": "string", 
            "pattern": "^\\d{4}\\-(0?[1-9]|1[012])\\-(0?[1-9]|[12][0-9]|3[01])$"
        },

        "multilingualStringType": {
            "$comment": "Type for language support.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "languageCode": {"type": "string",
                        "enum": ["no", "nb", "nn", "en"]},
                    "value": {"type": "string"}
                },
                "required": [
                    "languageCode",
                    "value"
                ]
            }
        },

        "codeListType": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "topLevelCodeItems": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "code": {"type": "string"},
                            "categoryTitle": {"$ref": "#/definitions/multilingualStringType"},
                            "validityPeriodStart": {"$ref": "#/definitions/dateType"},
                            "validityPeriodStop": {"$ref": "#/definitions/dateType"}
                        },
                        "required": [
                            "code",
                            "categoryTitle",
                            "validityPeriodStart"
                        ]
                    }
                }
            },
            "required": [
                "name",
                "topLevelCodeItems"
            ]
        },

        "valueDomainType": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "title": {"$ref": "#/definitions/multilingualStringType"},
                "description": {"$ref": "#/definitions/multilingualStringType"},
                "uriDefinition": {
                    "type": "array",
                    "items": [
                        {"type": [ "string", "null" ]}
                    ]
                },
                "codeList": {"$ref": "#/definitions/codeListType"},
                "measurementUnitDescription": {"$ref": "#/definitions/multilingualStringType"}
            },
            "required": [
                "name",
                "title"
            ]
        },

        "unitTypeType": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "title": {"$ref": "#/definitions/multilingualStringType"},
                "description": {"$ref": "#/definitions/multilingualStringType"}
            },
            "required": [
                "name",
                "title",
                "description"
            ]
        },

        "subjectFieldType": {
            "type": "array",
            "items": [
                {
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"},
                        "title": {"$ref": "#/definitions/multilingualStringType"},
                        "description": {"$ref": "#/definitions/multilingualStringType"}
                    },
                    "required": [
                        "name",
                        "title",
                        "description"
                    ]
                }
            ]
        }
    },

    
    "type": "object",
    "properties": {
        "name": {"type": "string"},
        "title": {"$ref": "#/definitions/multilingualStringType"},
        "description": {"$ref": "#/definitions/multilingualStringType"},
        "populationDescription": {"$ref": "#/definitions/multilingualStringType"},
        "temporalityType": {"type": "string",
            "enum": ["FIXED", "STATUS", "ACCUMULATED", "EVENT"]
        },
        "spatialCoverageDescription": {"$ref": "#/definitions/multilingualStringType"},
        "dataRevision": {
            "type": "object",
            "properties": {
                "version": {"type": "string",
                    "pattern": "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$"
                },
                "releaseStatus": {"type": "string",
                    "enum": ["DRAFT", "PENDING_RELEASE", "RELEASED", "PENDING_DELETE", "DELETED"]
                },
                "operationType": {"type": "string",
                    "enum": ["ADD", "REMOVE", "CHANGE_DATA", "CHANGE_METADATA", "PATCH"]
                },
                "description": {"$ref": "#/definitions/multilingualStringType"},
                "temporalCoverageStart": {"$ref": "#/definitions/dateType"},
                "temporalEndOfSeries": {"type": "boolean"},
                "releaseDate": {"$ref": "#/definitions/dateType"},
                "temporalCoverageLatest": {"$ref": "#/definitions/dateType"},
                "temporalStatusDates": {
                    "type": "array",
                    "items": {"$ref": "#/definitions/dateType"}
                }
            },
            "required": [
                "version",
                "releaseStatus",
                "operationType",
                "description",
                "temporalCoverageStart",
                "temporalEndOfSeries",
                "releaseDate",
                "temporalCoverageLatest"
            ]
        },
        "measure": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "title": {"$ref": "#/definitions/multilingualStringType"},
                "description": {"$ref": "#/definitions/multilingualStringType"},
                "uriDefinition": {
                    "type": "array",
                    "items": {"type": ["string", "null"] }
                },
                "dataType": {"type": "string",
                    "enum": ["STRING", "LONG", "DOUBLE", "DATE"]
                },
                "subjectField": {"$ref": "#/definitions/subjectFieldType"},
                "valueDomain": {"$ref": "#/definitions/valueDomainType"},
                "format": {"type": "string",
                    "enum": ["RandomUInt48"]
                },
                "unitType": {"$ref": "#/definitions/unitTypeType"},
                "sentinelAndMissingValueDomain": {"$ref": "#/definitions/valueDomainType"}
            },
            "required": [
                "name",
                "uriDefinition",
                "dataType",
                "subjectField",
                "valueDomain"
            ]
        },
        "ssbProperty": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "key": {"type": "string"},
                    "value": {"type": "string"}
                },
                "required": [
                    "key",
                    "value"
                ]
            }
        },
        "identifier": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "title": {"$ref": "#/definitions/multilingualStringType"},
                    "description": {"$ref": "#/definitions/multilingualStringType"},
                    "format": {"type": "string",
                        "enum": ["RandomUInt48"]
                    },
                    "unitType": {"$ref": "#/definitions/unitTypeType"},
                    "valueDomain": {"$ref": "#/definitions/valueDomainType"}
                },
                "required": [
                    "name",
                    "title",
                    "description",
                    "format",
                    "unitType",
                    "valueDomain"
                ]
            }
        },
        "attribute": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "title": {"$ref": "#/definitions/multilingualStringType"},
                    "description": {"$ref": "#/definitions/multilingualStringType"},
                    "dataType": {"type": "string",
                        "enum": ["STRING", "LONG", "DOUBLE", "DATE"]
                    },
                    "attributeType": {"type": "string",
                        "enum": ["START", "STOP", "QUALITY", "SOURCE", "OTHER"]},
                    "valueDomain": {"$ref": "#/definitions/valueDomainType"},
                    "format": {"type": "string"}
                },
                "required": [
                    "name",
                    "title",
                    "description",
                    "dataType",
                    "attributeType",
                    "valueDomain"
                ]
            }
        }
    },
    "required": [
        "name",
        "title",
        "description",
        "populationDescription",
        "temporalityType",
        "spatialCoverageDescription",
        "dataRevision",
        "measure",
        "identifier",
        "attribute"
    ]
}

=== statisticsnorway/microdata-datastore-builder/tests/resources/TEST_PERSON_INCOME.json
{
    "name": "TEST_PERSON_INCOME",
    "title": [
        {"languageCode": "no", "value": "Inntekt"},
        {"languageCode": "en", "value": "Income"}
    ],
    "description": [
        {"languageCode": "no", "value": "Personinntekt."},
        {"languageCode": "en", "value": "Personal income."}
    ],
    "populationDescription": [
        {"languageCode": "no", "value": "Alle personer med inntekt."},
        {"languageCode": "en", "value": "All persons with income."}
    ],
    "temporalityType": "ACCUMULATED",
    "spatialCoverageDescription": [
        {"languageCode": "no", "value": "Norge"},
        {"languageCode": "en", "value": "Norway"}
    ],    
    "dataRevision": {
        "version": "1.0.0",
        "releaseStatus": "RELEASED",
        "operationType": "ADD",
        "releaseDate": "2020-03-25",
        "description": [
            {"languageCode": "no", "value": "Første versjon av datasettet."},
            {"languageCode": "en", "value": "The initial version of this dataset."}
        ],  
        "temporalCoverageStart": "2016-01-01",
        "temporalEndOfSeries": false,
        "temporalCoverageLatest": "2019-12-31"
    },
    "measure": {
        "name": "TEST_PERSON_INCOME",
        "uriDefinition": ["https://data.skatteetaten.no/begrep/personinntekt%20fra%20l%C3%B8nnsinntekt"],
        "dataType": "LONG",
        "subjectField": [
            {
                "name": "INCOME_PROPERTY_TAX",
                "title": [
                    {"languageCode": "no", "value": "Inntekt"},
                    {"languageCode": "en", "value": "Income"}
                ],
                "description": [
                    {"languageCode": "no", "value": "Innekt, formue, skatt"},
                    {"languageCode": "en", "value": "Income, property, taxes"}
                ]
            }
        ],
        "valueDomain": {
            "name": "INCOME",
            "title": [
                {"languageCode": "no", "value": "Personinntekt i norske kroner (NOK)."},
                {"languageCode": "en", "value": "Personal income in Norwegian kroner (NOK)."}
            ],
            "uriDefinition": [null]
        }
    },
    "identifier": [
        {
            "name": "PERSON_ID_1",
            "title": [
                {"languageCode": "no", "value": "Personidentifikator"},
                {"languageCode": "en", "value": "National identity number"}
            ],
            "description": [
                {"languageCode": "no", "value": "Identifikator for person"},
                {"languageCode": "en", "value": "Persons national identity number"}
            ],
            "format": "RandomUInt48",
            "unitType": {
                "name": "PERSON",
                "title": [
                    {"languageCode": "no", "value": "Person"},
                    {"languageCode": "en", "value": "Person"}
                ],
                "description": [
                    {"languageCode": "no", "value": "Statistisk enhet er person (individ, enkeltmenneske)."},
                    {"languageCode": "en", "value": "Statistical unit is person"}
                ]
            },
            "valueDomain": {
                "name": "FOEDSELSNUMMER",
                "title": [
                    {"languageCode": "no", "value": "Pseudonymisert fødselsnummer"},
                    {"languageCode": "en", "value": "Pseudonym for persons national identity number"}
                ],
                "uriDefinition": [
                    "http://www.ssb.no/a/metadata/conceptvariable/vardok/26/nb", 
                    "https://www.ssb.no/a/metadata/conceptvariable/vardok/26/en"
                ],
                "measurementUnitDescription": [
                    {"languageCode": "no", "value": "N/A"},
                    {"languageCode": "en", "value": "N/A"}
                ]
            }
        }
    ],
    "attribute": [
        {
            "name": "START",
            "title": [
                {"languageCode": "no", "value": "Startdato"},
                {"languageCode": "en", "value": "Start date"}
            ],
            "description": [
                {"languageCode": "no", "value": "Startdato/måletidspunktet for hendelsen"},
                {"languageCode": "en", "value": "Event start date"}
            ],
            "dataType": "DATE",
            "attributeType": "START",
            "valueDomain": {
                "name": "START_DATE_EVENT",
                "title": [
                    {"languageCode": "no", "value": "Startdato"},
                    {"languageCode": "en", "value": "Start date"}
                ],
                "uriDefinition": [null],
                "measurementUnitDescription": [
                    {"languageCode": "no", "value": "N/A"},
                    {"languageCode": "en", "value": "N/A"}
                ]
            }
        },
        {
            "name": "STOP",
            "title": [
                {"languageCode": "no", "value": "Stoppdato"},
                {"languageCode": "en", "value": "Stop date"}
            ],
            "description": [
                {"languageCode": "no", "value": "Stoppdato/sluttdato for hendelsen"},
                {"languageCode": "en", "value": "Event stop/end date"}
            ],
            "dataType": "DATE",
            "attributeType": "STOP",
            "valueDomain": {
                "name": "STOP_DATE_EVENT",
                "title": [
                    {"languageCode": "no", "value": "Stoppdato/sluttdato"},
                    {"languageCode": "en", "value": "Stop/end date"}
                ],
                "uriDefinition": [null],
                "measurementUnitDescription": [
                    {"languageCode": "no", "value": "N/A"},
                    {"languageCode": "en", "value": "N/A"}
                ]
            }
        }
    ]
}

=== statisticsnorway/microdata-datastore-builder/validate/TestMetadata_BEFOLKNING_BARN3_I_FAM.json
{
    "name": "BEFOLKNING_BARN3_I_FAM",
    "title": [
        {"languageCode": "no", "value": "Antall barn i familien, uansett alder"},
        {"languageCode": "en", "value": "This is title in english bla, bla, bla ............"}
    ],
    "description": [
        {"languageCode": "no", "value": "Som barn regnes her alle personer, uansett alder, som er registrert bosatt i familien til minst en av foreldrene. Familie er definert som personer som er bosatt i samme bolig og som er knyttet til hverandre som ektefeller, registrerte partnere, samboere og/eller som foreldre og barn (uansett barnets alder). \n \n Variabelen omfatter bosatte per 01.01.ÅÅÅÅ, avgrenset til privathusholdninger."},
        {"languageCode": "en", "value": "This is description in english bla, bla, bla ............"}
    ],
    "populationDescription": [
        {"languageCode": "no", "value": "Variabelen omfatter bosatte per 1.1.ÅÅÅÅ, avgrenset til privathusholdninger."},
        {"languageCode": "en", "value": "This is populationDescription in english bla, bla, bla ............"}
    ],
    "temporalityType": "STATUS",
    "spatialCoverageDescription": [
        {"languageCode": "no", "value": "Norge"},
        {"languageCode": "en", "value": "Norway"}
    ],    
    "dataRevision": {
        "version": "2.0.0",
        "releaseStatus": "RELEASED",
        "operationType": "CHANGE_DATA",
        "description": [
            {"languageCode": "no", "value": "Nye årganger. Endret populasjon, nå inkludert alle verdier."},
            {"languageCode": "en", "value": "This is dataRevision.description in english bla, bla, bla ............"}
        ],  
        "temporalCoverageStart": "2005-01-01",
        "temporalEndOfSeries": false,
        "releaseDate": "2017-01-01",
        "temporalCoverageLatest": "2020-01-01",
        "temporalStatusDates": [
            "2009-01-01",
            "2013-01-01",
            "2007-01-01",
            "2015-01-01",
            "2012-01-01",
            "2016-01-01",
            "2006-01-01",
            "2014-01-01",
            "2019-01-01",
            "2018-01-01",
            "2005-01-01",
            "2010-01-01",
            "2011-01-01",
            "2008-01-01",
            "2020-01-01",
            "2017-01-01"
        ]
    },
    "measure": {
        "name": "BEFOLKNING_BARN3_I_FAM",
        "uriDefinition": [
            "https://www.ssb.no/a/metadata/conceptvariable/vardok/932/nb"
        ],
        "dataType": "STRING",
        "subjectField": [
            {
                "name": "FAMILIE",
                "title": [
                    {"languageCode": "no", "value": "Familie"},
                    {"languageCode": "en", "value": "Familie"}
                ],
                "description": [
                    {"languageCode": "no", "value": "Familie"},
                    {"languageCode": "en", "value": "Familie"}
                ]
            },
            {
                "name": "BEFOLKNING",
                "title": [
                    {"languageCode": "no", "value": "Befolkning"},
                    {"languageCode": "en", "value": "Population"}
                ],
                "description": [
                    {"languageCode": "no", "value": "Befolkning"},
                    {"languageCode": "en", "value": "Population"}
                ]
            },
            {
                "name": "HUSHOLDNING",
                "title": [
                    {"languageCode": "no", "value": "Husholdning"},
                    {"languageCode": "en", "value": "Household"}
                ],
                "description": [
                    {"languageCode": "no", "value": "Husholdning"},
                    {"languageCode": "en", "value": "Household"}
                ]
            }
        ],
        "valueDomain": {
            "name": "ANTALL_BARN",
            "title": [
                {"languageCode": "no", "value": "Antall barn"},
                {"languageCode": "en", "value": "Number of children"}
            ],
            "uriDefinition": [null],
            "codeList": {
                "name": "ANTALL_BARN",
                "topLevelCodeItems": [
                    {
                        "code": "1",
                        "categoryTitle": [
                            {"languageCode": "no", "value": "Ett barn"},
                            {"languageCode": "en", "value": "One child"}
                        ],
                        "validityPeriodStart": "1992-01-01"
                    },
                    {
                        "code": "2",
                        "categoryTitle": [
                            {"languageCode": "no", "value": "To barn"},
                            {"languageCode": "en", "value": "Two children"}
                        ],
                        "validityPeriodStart": "1992-01-01"
                    },
                    {
                        "code": "3",
                        "categoryTitle": [
                            {"languageCode": "no", "value": "Tre eller flere barn"},
                            {"languageCode": "en", "value": "Three or more children"}
                        ],
                        "validityPeriodStart": "1992-01-01"
                    }
                ]
            }
        }
    },
    "ssbProperty": [
        {
            "key": "GENERERT",
            "value": "27 Februar 2020"
        },
        {
            "key": "KILDE_FIL",
            "value": "($BESTAT/familie/wk14/hush_fam_samord_bolig) (2014-)"
        },
        {
            "key": "KILDE_FIL",
            "value": "$BESTAT/familie/arkiv/hush_fam_formell (2005-2013)"
        }
    ],
    "identifier": [
        {
            "name": "PERSONID_1",
            "title": [
                {"languageCode": "no", "value": "Personidentifikator"},
                {"languageCode": "en", "value": "National identity number"}
            ],
            "description": [
                {"languageCode": "no", "value": "Identifikator for person"},
                {"languageCode": "en", "value": "Persons national identity number"}
            ],
            "format": "RandomUInt48",
            "unitType": {
                "name": "PERSON",
                "title": [
                    {"languageCode": "no", "value": "Person"},
                    {"languageCode": "en", "value": "Person"}
                ],
                "description": [
                    {"languageCode": "no", "value": "Statistisk enhet er person (individ, enkeltmenneske)."},
                    {"languageCode": "en", "value": "Statistical unit is person"}
                ]
            },
            "valueDomain": {
                "name": "FOEDSELSNUMMER",
                "title": [
                    {"languageCode": "no", "value": "Pseudonymisert fødselsnummer"},
                    {"languageCode": "en", "value": "Pseudonym for persons national identity number"}
                ],
                "uriDefinition": [
                    "http://www.ssb.no/a/metadata/conceptvariable/vardok/26/nb"
                ],
                "measurementUnitDescription": [
                    {"languageCode": "no", "value": "N/A"},
                    {"languageCode": "en", "value": "N/A"}
                ]
            }
        }
    ],
    "attribute": [
        {
            "name": "START",
            "title": [
                {"languageCode": "no", "value": "Startdato"},
                {"languageCode": "en", "value": "Start date"}
            ],
            "description": [
                {"languageCode": "no", "value": "Startdato/måletidspunktet for hendelsen"},
                {"languageCode": "en", "value": "Event start date"}
            ],
            "dataType": "DATE",
            "attributeType": "START",
            "valueDomain": {
                "name": "START_DATE_EVENT",
                "title": [
                    {"languageCode": "no", "value": "Startdato"},
                    {"languageCode": "en", "value": "Start date"}
                ],
                "uriDefinition": [null],
                "measurementUnitDescription": [
                    {"languageCode": "no", "value": "N/A"},
                    {"languageCode": "en", "value": "N/A"}
                ]
            }
        },
        {
            "name": "STOP",
            "title": [
                {"languageCode": "no", "value": "Stoppdato"},
                {"languageCode": "en", "value": "Stop date"}
            ],
            "description": [
                {"languageCode": "no", "value": "Stoppdato/sluttdato for hendelsen"},
                {"languageCode": "en", "value": "Event stop/end date"}
            ],
            "dataType": "DATE",
            "attributeType": "STOP",
            "valueDomain": {
                "name": "STOP_DATE_EVENT",
                "title": [
                    {"languageCode": "no", "value": "Stoppdato/sluttdato"},
                    {"languageCode": "en", "value": "Stop/end date"}
                ],
                "uriDefinition": [null],
                "measurementUnitDescription": [
                    {"languageCode": "no", "value": "N/A"},
                    {"languageCode": "en", "value": "N/A"}
                ]
            }
        }
    ]
}
